version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: restaurino
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    networks:
      - restaurino_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: dev
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    networks:
      - restaurino_network

networks:
  restaurino_network:

volumes:
  mysql_data:
