version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: restaurino
#    MYSQL_USER: root
#    MYSQL_PASSWORD: dev
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
